# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elimination_mat <- function(n) {
    .Call(`_MSCMGARCH_elimination_mat`, n)
}

commutation_mat <- function(n) {
    .Call(`_MSCMGARCH_commutation_mat`, n)
}

duplication_mat <- function(n) {
    .Call(`_MSCMGARCH_duplication_mat`, n)
}

inv_gen <- function(m) {
    .Call(`_MSCMGARCH_inv_gen`, m)
}

expected_indicator_value <- function(r, signs) {
    .Call(`_MSCMGARCH_expected_indicator_value`, r, signs)
}

loglike_bekk <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_bekk`, theta, r)
}

loglike_asymm_bekk <- function(theta, r, signs) {
    .Call(`_MSCMGARCH_loglike_asymm_bekk`, theta, r, signs)
}

score_bekk <- function(theta, r) {
    .Call(`_MSCMGARCH_score_bekk`, theta, r)
}

score_asymm_bekk <- function(theta, r, signs) {
    .Call(`_MSCMGARCH_score_asymm_bekk`, theta, r, signs)
}

bhh_bekk <- function(r, theta, max_iter, crit) {
    .Call(`_MSCMGARCH_bhh_bekk`, r, theta, max_iter, crit)
}

bhh_asymm_bekk <- function(r, theta, max_iter, crit, signs) {
    .Call(`_MSCMGARCH_bhh_asymm_bekk`, r, theta, max_iter, crit, signs)
}

random_grid_search_BEKK <- function(r) {
    .Call(`_MSCMGARCH_random_grid_search_BEKK`, r)
}

random_grid_search_asymmetric_BEKK <- function(r, signs) {
    .Call(`_MSCMGARCH_random_grid_search_asymmetric_BEKK`, r, signs)
}

sigma_bekk <- function(r, C, A, G) {
    .Call(`_MSCMGARCH_sigma_bekk`, r, C, A, G)
}

sigma_bekk_asymm <- function(r, C, A, B, G, signs) {
    .Call(`_MSCMGARCH_sigma_bekk_asymm`, r, C, A, B, G, signs)
}

hesse_bekk <- function(theta, r) {
    .Call(`_MSCMGARCH_hesse_bekk`, theta, r)
}

hesse_asymm_bekk <- function(theta, r, signs) {
    .Call(`_MSCMGARCH_hesse_asymm_bekk`, theta, r, signs)
}

pnorm_cpp <- function(r) {
    .Call(`_MSCMGARCH_pnorm_cpp`, r)
}

dnorm_cpp <- function(r) {
    .Call(`_MSCMGARCH_dnorm_cpp`, r)
}

gumbelCDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelCDF`, u1, u2, theta)
}

gumbelPDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelPDF`, u1, u2, theta)
}

gumbelH1 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelH1`, u1, u2, theta)
}

gumbelH2 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelH2`, u1, u2, theta)
}

claytonCDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonCDF`, u1, u2, theta)
}

claytonPDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonPDF`, u1, u2, theta)
}

claytonH1 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonH1`, u1, u2, theta)
}

claytonH2 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonH2`, u1, u2, theta)
}

copulaPDF <- function(u1, u2, theta, type) {
    .Call(`_MSCMGARCH_copulaPDF`, u1, u2, theta, type)
}

copulaH1 <- function(u1, u2, theta, type) {
    .Call(`_MSCMGARCH_copulaH1`, u1, u2, theta, type)
}

copulaH2 <- function(u1, u2, theta, type) {
    .Call(`_MSCMGARCH_copulaH2`, u1, u2, theta, type)
}

VineH2 <- function(u1, u2, u3, copula_par, type) {
    .Call(`_MSCMGARCH_VineH2`, u1, u2, u3, copula_par, type)
}

VineCopula <- function(u, copula_par, type) {
    .Call(`_MSCMGARCH_VineCopula`, u, copula_par, type)
}

eigen_value_decomposition <- function(A) {
    .Call(`_MSCMGARCH_eigen_value_decomposition`, A)
}

loglike_Normal_Gumbel_GumbelSurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel_GumbelSurvival`, bekk, theta, r)
}

loglike_Normal_Gumbel_Clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel_Clayton`, bekk, theta, r)
}

loglike_Normal_GumbelS_ClaytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_GumbelS_ClaytonS`, bekk, theta, r)
}

loglike_Normal_Clayton_ClaytonSurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Clayton_ClaytonSurvival`, bekk, theta, r)
}

loglike_Clayton_Gumbel <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Clayton_Gumbel`, bekk, theta, r)
}

loglike_Clayton_Gumbel90 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Clayton_Gumbel90`, bekk, theta, r)
}

loglike_Normal_Gumbel <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel`, bekk, theta, r)
}

loglike_Normal_GumbelS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_GumbelS`, bekk, theta, r)
}

loglike_Normal_Gumbel1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel1`, bekk, theta, r)
}

loglike_Normal_GumbelS1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_GumbelS1`, bekk, theta, r)
}

loglike_Normal_Frank <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Frank`, bekk, theta, r)
}

loglike_Normal_Clayton1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Clayton1`, bekk, theta, r)
}

loglike_Normal_ClaytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_ClaytonS`, bekk, theta, r)
}

loglike_Normal_Clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Clayton`, bekk, theta, r)
}

loglike_Normal_ClaytonS1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_ClaytonS1`, bekk, theta, r)
}

random_grid_search_clayton_gumbel <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_clayton_gumbel`, bekk, theta, r, nc)
}

random_grid_search_normal_gumbel <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel`, bekk, theta, r, nc)
}

random_grid_search_normal_gumbel1 <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel1`, bekk, theta, r, nc)
}

random_grid_search_normal_gumbelS <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbelS`, bekk, theta, r, nc)
}

random_grid_search_normal_clayton <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_clayton`, bekk, theta, r, nc)
}

random_grid_search_normal_claytonS <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_claytonS`, bekk, theta, r, nc)
}

random_grid_search_normal_frank <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_frank`, bekk, theta, r, nc)
}

random_grid_search_clayton_gumbel90 <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_clayton_gumbel90`, bekk, theta, r, nc)
}

random_grid_search_normal_gumbel_gumbelsurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel_gumbelsurvival`, bekk, theta, r)
}

random_grid_search_normal_gumbelS_claytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbelS_claytonS`, bekk, theta, r)
}

random_grid_search_normal_gumbel_clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel_clayton`, bekk, theta, r)
}

random_grid_search_normal_clayton_claytonsurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_clayton_claytonsurvival`, bekk, theta, r)
}

FilterProbs_normal_clayton_claytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_clayton_claytonS`, bekk, theta, r)
}

FilterProbs_normal_gumbel_clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_gumbel_clayton`, bekk, theta, r)
}

FilterProbs_normal_gumbelS_claytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_gumbelS_claytonS`, bekk, theta, r)
}

FilterProbs_normal_gumbel_gumbelS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_gumbel_gumbelS`, bekk, theta, r)
}

FilterProbs_Clayton_Gumbel90 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Clayton_Gumbel90`, bekk, theta, r)
}

FilterProbs_Normal_Gumbel <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Gumbel`, bekk, theta, r)
}

FilterProbs_Normal_Clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Clayton`, bekk, theta, r)
}

FilterProbs_Normal_GumbelS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_GumbelS`, bekk, theta, r)
}

FilterProbs_Normal_ClaytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_ClaytonS`, bekk, theta, r)
}

FilterProbs_Normal_Frank <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Frank`, bekk, theta, r)
}

loglike_LL_Gumbel <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_Gumbel`, theta, r)
}

loglike_LL_GumbelS <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_GumbelS`, theta, r)
}

loglike_LL_Clayton <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_Clayton`, theta, r)
}

loglike_LL_ClaytonS <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_ClaytonS`, theta, r)
}

loglike_LL_Frank <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_Frank`, theta, r)
}

comp_bekk_forecast <- function(bekk, r) {
    .Call(`_MSCMGARCH_comp_bekk_forecast`, bekk, r)
}

comp_asymm_bekk_forecast <- function(bekk, r, signs) {
    .Call(`_MSCMGARCH_comp_asymm_bekk_forecast`, bekk, r, signs)
}

copula_cor <- function(theta, type) {
    .Call(`_MSCMGARCH_copula_cor`, theta, type)
}

cor_mat <- function(theta, type) {
    .Call(`_MSCMGARCH_cor_mat`, theta, type)
}

loglike_Normal_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_3`, bekk, theta, r, type)
}

loglike_Normal_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_3_asymm`, bekk, signs, theta, r, type)
}

loglike_Normal_Copula_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_Copula_3`, bekk, theta, r, type)
}

loglike_Normal_Copula_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_Copula_3_asymm`, bekk, signs, theta, r, type)
}

LL_loglike_Copula_3 <- function(theta, r, type) {
    .Call(`_MSCMGARCH_LL_loglike_Copula_3`, theta, r, type)
}

LL_loglike_Copula_3_asymm <- function(theta, signs, r, type) {
    .Call(`_MSCMGARCH_LL_loglike_Copula_3_asymm`, theta, signs, r, type)
}

random_grid_search_normal_copula_3 <- function(bekk, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_3`, bekk, theta, type, r, nc)
}

random_grid_search_normal_copula_copula_3 <- function(bekk, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_copula_3`, bekk, theta, type, r, nc)
}

random_grid_search_normal_copula_3_asymm <- function(bekk, signs, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_3_asymm`, bekk, signs, theta, type, r, nc)
}

random_grid_search_normal_copula_copula_3_asymm <- function(bekk, signs, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_copula_3_asymm`, bekk, signs, theta, type, r, nc)
}

FilterProbs_Normal_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_3`, bekk, theta, r, type)
}

FilterProbs_Normal_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_3_asymm`, bekk, signs, theta, r, type)
}

FilterProbs_Normal_Copula_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_Copula_3`, bekk, theta, r, type)
}

FilterProbs_Normal_Copula_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_Copula_3_asymm`, bekk, signs, theta, r, type)
}

random_grid_search_LL_copula_3 <- function(theta, r, type, nc) {
    .Call(`_MSCMGARCH_random_grid_search_LL_copula_3`, theta, r, type, nc)
}

random_grid_search_LL_copula_3_asymm <- function(theta, signs, r, type, nc) {
    .Call(`_MSCMGARCH_random_grid_search_LL_copula_3_asymm`, theta, signs, r, type, nc)
}

